"""empty message

Revision ID: 0160e6cee45e
Revises: e911658f6057
Create Date: 2024-09-15 11:27:18.133034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0160e6cee45e'
down_revision = 'e911658f6057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
