"""empty message

Revision ID: 01ffcbcd7e64
Revises: 571328b86d7a
Create Date: 2024-09-06 18:06:32.431053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01ffcbcd7e64'
down_revision = '571328b86d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mystery_boxes', schema=None) as batch_op:
        batch_op.alter_column('revenue',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mystery_boxes', schema=None) as batch_op:
        batch_op.alter_column('revenue',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
