"""empty message

Revision ID: 2a9b7e26fb2e
Revises: b0159ac8f4d5
Create Date: 2024-09-02 12:51:46.606798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a9b7e26fb2e'
down_revision = 'b0159ac8f4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=False))
        batch_op.add_column(sa.Column('business_core', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('shop_description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('shop_summary', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('image_shop_url', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('owner_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('owner_surname', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_constraint('shop_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('shop_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('owner_surname')
        batch_op.drop_column('owner_name')
        batch_op.drop_column('image_shop_url')
        batch_op.drop_column('shop_summary')
        batch_op.drop_column('shop_description')
        batch_op.drop_column('business_core')
        batch_op.drop_column('categories')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
