"""empty message

Revision ID: 571328b86d7a
Revises: 84ca2666b107
Create Date: 2024-09-06 15:38:08.520093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571328b86d7a'
down_revision = '84ca2666b107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mystery_boxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revenue', sa.Float(), nullable=False))

    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['id'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_rate', sa.Float(), nullable=False))
        batch_op.drop_constraint('sales_shop_id_fkey', type_='foreignkey')
        batch_op.drop_column('shop_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('sales_shop_id_fkey', 'shops', ['shop_id'], ['id'])
        batch_op.drop_column('commission_rate')

    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shop_id')

    with op.batch_alter_table('mystery_boxes', schema=None) as batch_op:
        batch_op.drop_column('revenue')

    op.drop_table('shop_sales')
    # ### end Alembic commands ###
