"""empty message

Revision ID: 8386588e71f8
Revises: df12812b668c
Create Date: 2024-09-10 18:52:07.082232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8386588e71f8'
down_revision = 'df12812b668c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sale_detail_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('item_size', sa.String(length=20), nullable=False),
    sa.Column('item_category', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['sale_detail_id'], ['sale_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('box_item_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('original_item_name', sa.String(length=100), nullable=False),
    sa.Column('original_item_size', sa.String(length=20), nullable=False),
    sa.Column('original_item_category', sa.String(length=50), nullable=False),
    sa.Column('proposed_item_name', sa.String(length=100), nullable=False),
    sa.Column('proposed_item_size', sa.String(length=20), nullable=False),
    sa.Column('proposed_item_category', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['box_item_id'], ['box_items.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('item_change_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_change_request_id'], ['item_change_requests.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('item_change_requests')
    op.drop_table('box_items')
    # ### end Alembic commands ###
