"""empty message

Revision ID: 84ca2666b107
Revises: 2a9b7e26fb2e
Create Date: 2024-09-06 10:57:12.772976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84ca2666b107'
down_revision = '2a9b7e26fb2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('business_core', sa.Text(), nullable=False),
    sa.Column('shop_description', sa.Text(), nullable=False),
    sa.Column('shop_summary', sa.String(length=200), nullable=False),
    sa.Column('image_shop_url', sa.String(length=200), nullable=False),
    sa.Column('owner_name', sa.String(length=120), nullable=False),
    sa.Column('owner_surname', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('upper_size', sa.String(length=10), nullable=False),
    sa.Column('lower_size', sa.String(length=10), nullable=False),
    sa.Column('cap_size', sa.String(length=10), nullable=True),
    sa.Column('shoe_size', sa.String(length=10), nullable=False),
    sa.Column('not_colors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('stamps', sa.String(length=20), nullable=False),
    sa.Column('fit', sa.String(length=20), nullable=False),
    sa.Column('not_clothes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('profession', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mystery_boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('possible_items', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.Column('number_of_items', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('mystery_box_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(length=450), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mystery_box_id'], ['mystery_boxes.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('mystery_box_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['mystery_box_id'], ['mystery_boxes.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mystery_box')
    op.drop_table('shop')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('upper_size', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('lower_size', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('cup_size', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('shoe_size', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('not_colors', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('stamps', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('fit', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('not_clothes', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('categories', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('profession', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.create_table('shop',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('shop_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('business_core', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('shop_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('shop_summary', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('image_shop_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('owner_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('owner_surname', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='shop_pkey'),
    sa.UniqueConstraint('email', name='shop_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('mystery_box',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('possible_items', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('number_of_items', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], name='mystery_box_shop_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='mystery_box_pkey')
    )
    op.drop_table('sale_details')
    op.drop_table('ratings')
    op.drop_table('sales')
    op.drop_table('mystery_boxes')
    op.drop_table('users')
    op.drop_table('shops')
    # ### end Alembic commands ###
