"""empty message

Revision ID: b0159ac8f4d5
Revises: 
Create Date: 2024-09-01 10:34:34.419710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0159ac8f4d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('upper_size', sa.String(length=10), nullable=False),
    sa.Column('lower_size', sa.String(length=10), nullable=False),
    sa.Column('cup_size', sa.String(length=10), nullable=True),
    sa.Column('shoe_size', sa.String(length=10), nullable=False),
    sa.Column('not_colors', sa.String(length=100), nullable=True),
    sa.Column('stamps', sa.String(length=20), nullable=False),
    sa.Column('fit', sa.String(length=20), nullable=False),
    sa.Column('not_clothes', sa.String(length=100), nullable=True),
    sa.Column('categories', sa.String(length=200), nullable=False),
    sa.Column('profession', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mystery_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('possible_items', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.Column('number_of_items', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mystery_box')
    op.drop_table('shop')
    op.drop_table('user')
    # ### end Alembic commands ###
