"""empty message

Revision ID: e85ea8971286
Revises: 0160e6cee45e
Create Date: 2024-09-15 13:00:08.161200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e85ea8971286'
down_revision = '0160e6cee45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('ITEM_CHANGE_REQUEST', 'CHANGE_REQUEST_RESULT', 'ITEM_CHANGED', 'NEW_SALE', 'CONFIRMATION', name='notificationtype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ITEM_CHANGE_REQUEST', 'CHANGE_REQUEST_RESULT', 'ITEM_CHANGED', 'NEW_SALE', 'CONFIRMATION', name='notificationtype'),
               existing_nullable=False)
    # ### end Alembic commands ###
