"""empty message

Revision ID: fe61bd4acbf6
Revises: 6be4adc484cc
Create Date: 2024-09-11 08:13:25.639853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe61bd4acbf6'
down_revision = '6be4adc484cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('box_items', 'item_size')
    op.drop_column('box_items', 'item_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('box_items', sa.Column('item_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('box_items', sa.Column('item_size', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
